export const currencies = [
  {
    id: "22224",
    ID: "22224",
    symbol: "USD",
    amount: 0,
    label: "US Dollar",
    icon: "$",
    iconBg: "bg-green-500",
    iconImage: "/svgs/currency/usd.svg",
    value: "USD",
    type: "fiat",
    hasMethod: true,
    disabled: false,
    badgeLabel: "Available",
  },
  {
    id: "22225",
    ID: "22225",
    symbol: "EUR",
    amount: 0,
    label: "Euro",
    icon: "€",
    iconBg: "bg-blue-500",
    iconImage: "/svgs/currency/eur.svg",
    value: "EUR",
    type: "fiat",
    hasMethod: false,
    disabled: true,
    badgeLabel: "Not Available",
  },
  {
    id: "22226",
    ID: "22226",
    symbol: "BTC",
    amount: 0,
    label: "Bitcoin",
    icon: "₿",
    iconBg: "bg-orange-500",
    iconImage: "/svgs/currency/btc.svg",
    value: "BTC",
    type: "crypto",
    hasMethod: false,
    disabled: true,
    badgeLabel: "Not Available",
  },
  {
    id: "22227",
    ID: "22227",
    symbol: "ETH",
    amount: 0,
    label: "Ethereum",
    icon: "Ξ",
    iconBg: "bg-gray-700",
    iconImage: "/svgs/currency/eth.svg",
    value: "ETH",
    type: "crypto",
    hasMethod: false,
    disabled: true,
    badgeLabel: "Not Available",
  },
  {
    id: "22228",
    ID: "22228",
    symbol: "LTC",
    amount: 0,
    label: "Litecoin",
    icon: "Ł",
    iconBg: "bg-blue-600",
    iconImage: "/svgs/currency/ltc.svg",
    value: "LTC",
    type: "crypto",
    hasMethod: false,
    disabled: true,
    badgeLabel: "Not Available",
  },
  {
    id: "22229",
    ID: "22229",
    symbol: "BCH",
    amount: 0,
    label: "Bitcoin Cash",
    icon: "₿",
    iconBg: "bg-green-600",
    iconImage: "/svgs/currency/bch.svg",
    value: "BCH",
    type: "crypto",
    hasMethod: false,
    disabled: true,
    badgeLabel: "Not Available",
  },
  {
    id: "22230",
    ID: "22230",
    symbol: "XRP",
    amount: 0,
    label: "Ripple",
    icon: "XRP",
    iconBg: "bg-blue-600",
    iconImage: "/svgs/currency/xrp.svg",
    value: "XRP",
    type: "crypto",
    hasMethod: false,
    disabled: true,
    badgeLabel: "Not Available",
  },
  {
    id: "1",
    symbol: "AED",
    amount: 0,
    label: "United Arab Emirates Dirham",
    icon: "AED",
    iconBg: "bg-green-500",
    iconImage: "/svgs/currency/aed.svg",
    value: "AED",
    type: "fiat",
    hasMethod: true,
    disabled: false,
    badgeLabel: "Available",
  },
  {
    id: "3",
    label: "INR",
    value: "INR",
    iconImage: "/svgs/currency/inr.svg",
    description: "Indian Rupee",
    disabled: false,
    badgeLabel: "Available",
    hasMethod: true,
    symbol: "INR",
    amount: 0,
    type: "fiat",
    
  },
  {
    id: "2",
    label: "USDT",
    value: "USDT",
    symbol: "USDT",
    amount: 0,
    iconImage: "/svgs/currency/usdt.svg",
    description: "Tether USD",
    disabled: false,
    badgeLabel: "Available",
    type: "crypto",
  },
];

export const fromCurrencies = [
  {
    id: "1",
    label: "AED",
    value: "AED",
    iconImage: "/svgs/currency/aed.svg",
    description: "United Arab Emirates Dirham",
    disabled: false,
    badgeLabel: "Available",
  },
  {
    id: "2",
    label: "USDT",
    value: "USDT",
    iconImage: "/svgs/currency/usdt.svg",
    description: "Tether USD",
    disabled: false,
    badgeLabel: "Available",
  },
  {
    id: "3",
    label: "INR",
    value: "INR",
    iconImage: "/svgs/currency/inr.svg",
    description: "Indian Rupee",
    disabled: false,
    badgeLabel: "Available",
  },
  {
    id: "4",
    label: "USD",
    value: "USD",
    iconImage: "/svgs/currency/usd.svg",
    description: "United States Dollar",
    disabled: false,
    badgeLabel: "Available",
  },
];

export type TCurrency = (typeof fromCurrencies)[0];

export const currencyImages = {
  AED: "/svgs/currency/aed.svg",
  USD: "/svgs/currency/usd.svg",
  INR: "/svgs/currency/inr.svg",
  EUR: "/svgs/currency/eur.svg",
  BTC: "/svgs/currency/btc.svg",
  ETH: "/svgs/currency/eth.svg",
  LTC: "/svgs/currency/ltc.svg",
  BCH: "/svgs/currency/bch.svg",
  XRP: "/svgs/currency/xrp.svg",
  USDT: "/svgs/currency/usdt.svg",
  USDC: "/svgs/currency/usdc.svg",
};

export const currencyDescriptions = {
  AED: "United Arab Emirates Dirham",
  USD: "United States Dollar",
  INR: "Indian Rupee",
  EUR: "Euro",
  BTC: "Bitcoin",
  ETH: "Ethereum",
  LTC: "Litecoin",
  BCH: "Bitcoin Cash",
  XRP: "Ripple",
  USDT: "Tether USD",
  USDC: "USD Coin",
};

export const USDCurrencies = [
  {
    id: "1",
    ID: "1",
    symbol: "USD",

    label: "US Dollar",
    icon: "$",
    iconBg: "bg-green-500",
    iconImage: "/svgs/currency/usd.svg",
    value: "USD",
    type: "fiat",
    hasMethod: true,
    disabled: false,
    badgeLabel: "Available",
  },
];

export const paymentMethods = [
  {
    id: "1",
    label: "Deposit With AED Bank",
    value: "AED",
    fromId: "1",
    iconImage: "/svgs/currency/1.png",
    description: "no commission",
    disabled: false,
    currency: "AED",
    badgeLabel: "Available",
  },
  {
    id: "2",
    label: "Deposit With Credit Or Debit Card",
    value: "CREDIT_DEBIT",
    fromId: "1",
    iconImage: "/svgs/currency/visa.jpeg",
    description: "no commission",
    disabled: false,
    currency: "AED",
    badgeLabel: "Available",
  },
  {
    id: "3",
    label: "Voucher Deposit",
    value: "VOUCHER",
    fromId: "1",
    iconImage: "/svgs/currency/voucher.png",
    description: "no commission",
    disabled: false,
    currency: "AED",
    badgeLabel: "Available",
  },
  {
    id: "4",
    label: "Deposit With USDT TRC20",
    value: "USDT_TRC20",
    fromId: "2",
    iconImage: "/svgs/currency/bank.svg",
    description: "Fee:1%",
    disabled: false,
    currency: "USDT",
    badgeLabel: "Available",
  },
  {
    id: "5",
    label: "Deposit With BUSDT-T-BSC",
    value: "BUSDT_TRC20",
    fromId: "2",
    iconImage: "/svgs/currency/bank.svg",
    description: "Fee:1%",
    disabled: false,
    currency: "USDT",
    badgeLabel: "Available",
  },
  {
    id: "6",
    label: "INR BANK",
    value: "INR BANK",
    fromId: "3",
    iconImage: "/svgs/currency/bank.svg",
    description: "no-commission",
    disabled: false,
    currency: "INR",
    badgeLabel: "Available",
  },
];

export const status = [
  {
    id: "1",
    label: "Pending",
    value: "PENDING",
  },
  {
    id: "2",
    label: "Completed",
    value: "COMPLETED",
  },
  {
    id: "3",
    label: "Failed",
    value: "FAILED",
  },
];

export const statusBadge: any = {
  pending: "warning",
  all: "default",
  submitted: "warning",
  completed: "success",
  failed: "destructive",
  success: "success",
  approved: "success",
  cancelled: "destructive",
  current: "default",
  rejected: "destructive",
  transfer_out: "warning",
  commission: "outline",
};
export const withdrawalMethods = [
  {
    id: "1",
    label: "Bank Transfer",
    value: "bank_transfer",
  },
  {
    id: "2",
    label: "Crypto",
    value: "crypto",
  },
  {
    id: "3",
    label: "Cash",
    value: "cash",
  },
];

// ERC20, TRC20, BEP20, Bitcoin, Ethereum, BSC, Polygon, Arbitrum, Optimism, Avalanche, Solana"

export const networks = [
  {
    id: "1",
    label: "ERC20",
    value: "ERC20",
  },
  {
    id: "2",
    label: "TRC20",
    value: "TRC20",
  },
  {
    id: "3",
    label: "BEP20",
    value: "BEP20",
  },
  {
    id: "4",
    label: "Bitcoin",
    value: "Bitcoin",
  },
  {
    id: "5",
    label: "Ethereum",
    value: "Ethereum",
  },
  {
    id: "6",
    label: "BSC",
    value: "BSC",
  },
  {
    id: "7",
    label: "Polygon",
    value: "Polygon",
  },
  {
    id: "8",
    label: "Arbitrum",
    value: "Arbitrum",
  },
  {
    id: "9",
    label: "Optimism",
    value: "Optimism",
  },
  {
    id: "10",
    label: "Avalanche",
    value: "Avalanche",
  },
  {
    id: "11",
    label: "Solana",
    value: "Solana",
  },
];

// passport, national_id, driving_license
export const collectorIdTypes = [
  {
    id: "1",
    label: "Passport",
    value: "passport",
  },
  {
    id: "2",
    label: "National ID",
    value: "national_id",
  },
  {
    id: "3",
    label: "Driving License",
    value: "driving_license",
  },
];

export const currencySymbols = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "$",
  CAD: "$",
  CHF: "₣",
  CNY: "¥",
  HKD: "HK$",
  INR: "₹",
  MXN: "MXN$",
  NZD: "$",
  RUB: "₽",
  SGD: "S$",
  ZAR: "R",
  BTC: "₿",
  ETH: "Ξ",
  LTC: "Ł",
  BCH: "₿",
  XRP: "XRP",
  DOGE: "DOGE",
  SHIB: "SHIB",
  XLM: "XLM",
  XMR: "XMR",
  USDT: "USDT",
  USDC: "USDC",
  AED: "AED",
};
